version: "3"
services:
  # Web Server
  nginx:
    container_name: nginx-e
    restart: unless-stopped
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports: 
      - "${APP_PORT}:80"
    volumes:
      - ./backend/:/var/www/html/
      - ./nginx/logs:/var/log/nginx/
    networks:
      - app-network
  # PHP Service
  php:
    container_name: php-e
    restart: unless-stopped
    build:
      context: .
      dockerfile: php/Dockerfile
    expose:
      - "9000"
    volumes:
      - ./backend/:/var/www/html/
      - ./php/logs:/var/log/fpm-php.www.log
      - ./.env:/var/www/html/.env
    depends_on:
      - mysql
    networks:
      - app-network
  # mySQL Service
  mysql:
    container_name: mysql-db-e
    restart: always
    image: mysql:latest
    platform: linux/x86_64
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/logs:/var/log/
    networks:
      - app-network
    environment:
      MYSQL_ROOT_PASSWORD: '1q2w3e4r'
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_TCP_PORT: ${DB_PORT}
# Docker networks
networks:
  app-network:
    driver: bridge